In [25]:
import cv2
import numpy as np

cap = cv2.VideoCapture('/content/262189_small.mp4')

if not cap.isOpened():
    print("Error: Could not open video file.")
else:
    ret, frame = cap.read()

    if ret:
        print("Original Frame (RGB) - First 5x5 pixels:\n")
        h, w, _ = frame.shape
        print(frame[:min(5, h), :min(5, w)])

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        print("\nGrayscale Frame - First 5x5 pixels:\n")
        print(gray_frame[:min(5, h), :min(5, w)])
    else:
        print("Error: Could not read a frame from the video. Make sure the video is not empty.")

    cap.release()

Original Frame (RGB) - First 5x5 pixels:

[[[112  91  61]
  [112  91  61]
  [113  92  62]
  [113  92  62]
  [114  93  63]]

 [[112  91  61]
  [113  92  62]
  [113  92  62]
  [113  92  62]
  [114  93  63]]

 [[113  92  62]
  [113  92  62]
  [114  93  63]
  [114  93  63]
  [115  94  64]]

 [[113  92  62]
  [113  92  62]
  [114  93  63]
  [114  93  63]
  [115  94  64]]

 [[114  93  63]
  [114  93  63]
  [115  94  64]
  [115  94  64]
  [116  95  65]]]

Grayscale Frame - First 5x5 pixels:

[[84 84 85 85 86]
 [84 85 85 85 86]
 [85 85 86 86 87]
 [85 85 86 86 87]
 [86 86 87 87 88]]


In [ ]:
from google.colab.patches import cv2_imshow

if 'frame' in locals() and frame is not None:
    print("Displaying the extracted frame:")
    cv2_imshow(frame)
else:
    print("Error: No frame found. Please make sure the previous cell was executed and a frame was successfully extracted.")

# Detecting edges with Canny

In [ ]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

input_video_path = '/content/262189_small.mp4'
output_video_path = '/content/canny_edges_video.avi' # Changed to .avi extension

cap = cv2.VideoCapture(input_video_path)

if not cap.isOpened():
    print(f"Error: Could not open video file at {input_video_path}")
else:
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    fourcc = cv2.VideoWriter_fourcc(*'XVID')

    out = cv2.VideoWriter(output_video_path, fourcc, fps, (frame_width, frame_height), isColor=False)

    if not out.isOpened():
        print("Error: Could not create video writer.")
    else:
        print(f"Processing video and saving to {output_video_path}...")
        frame_count = 0
        first_frame_displayed = False

        while True:
            ret, frame = cap.read()
            if not ret:
                break

            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            canny_edges = cv2.Canny(gray_frame, 100, 200)

            if not first_frame_displayed:
                print("\nPreview of the first processed frame:")
                cv2_imshow(canny_edges)
                first_frame_displayed = True

            out.write(canny_edges)

            frame_count += 1
            if frame_count % 100 == 0:
                print(f"Processed {frame_count} frames...")

        print(f"\nFinished processing {frame_count} frames. Video saved as {output_video_path}")

    cap.release()
    out.release()
    cv2.destroyAllWindows()


In [ ]:
from IPython.display import Video

Video('/content/262189_small.mp4', embed=True)


In [ ]:
Video('/content/canny_edges_video.avi', embed=True) # Changed to .avi extension

# next we need to convert to greyscale and get negative

In [34]:
if 'frame' in locals() and frame is not None:
    print(f"The video frame is successfully loaded and available. Shape: {frame.shape}")
else:
    print("Error: The 'frame' variable is not available or is None. Please re-execute cell '309f83ee' to load the first frame from the video.")

The video frame is successfully loaded and available. Shape: (1080, 2048, 3)


In [35]:
import cv2
import numpy as np

cap = cv2.VideoCapture('/content/262189_small.mp4')

if not cap.isOpened():
    print("Error: Could not open video file.")
else:
    ret, frame = cap.read()

    if ret:
        print("Original Frame (RGB) - First 5x5 pixels:\n")
        h, w, _ = frame.shape
        print(frame[:min(5, h), :min(5, w)])

        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        print("\nGrayscale Frame - First 5x5 pixels:\n")
        print(gray_frame[:min(5, h), :min(5, w)])
    else:
        print("Error: Could not read a frame from the video. Make sure the video is not empty.")

    cap.release()

Original Frame (RGB) - First 5x5 pixels:

[[[112  91  61]
  [112  91  61]
  [113  92  62]
  [113  92  62]
  [114  93  63]]

 [[112  91  61]
  [113  92  62]
  [113  92  62]
  [113  92  62]
  [114  93  63]]

 [[113  92  62]
  [113  92  62]
  [114  93  63]
  [114  93  63]
  [115  94  64]]

 [[113  92  62]
  [113  92  62]
  [114  93  63]
  [114  93  63]
  [115  94  64]]

 [[114  93  63]
  [114  93  63]
  [115  94  64]
  [115  94  64]
  [116  95  65]]]

Grayscale Frame - First 5x5 pixels:

[[84 84 85 85 86]
 [84 85 85 85 86]
 [85 85 86 86 87]
 [85 85 86 86 87]
 [86 86 87 87 88]]


In [ ]:
cv2_imshow(gray_frame)

In [37]:
negative_gray_frame = 255 - gray_frame

In [ ]:
cv2_imshow(negative_gray_frame)